<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/uploads.php';
require_once __DIR__ . '/../includes/stock.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/item_form.php';
require_once __DIR__ . '/../includes/audit.php';
require_once __DIR__ . '/../includes/assets.php';
require_role(['inventory_staff', 'admin']);

$pdo = get_db();
$user = current_user();
$errors = [];
$values = [
    'item_code' => '', 'name' => '', 'brand' => '', 'description' => '', 'specification' => '', 'category_id' => '',
    'unit' => 'pc', 'quantity_on_hand' => 0,
    'variant_label' => '', 'stall_layer_id' => '',
    'generate_qr' => false,
];
// Each: ['value' => string, 'qty' => int]. Re-populated from POST on a
// failed submit so the rows the user typed aren't lost.
$variant_rows = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_check($_POST['csrf_token'] ?? null)) {
        $errors[] = 'Your session expired. Please try again.';
    } else {
        $values['item_code']        = trim($_POST['item_code'] ?? '');
        $values['name']             = trim($_POST['name'] ?? '');
        $values['brand']            = trim($_POST['brand'] ?? '');
        $values['description']      = trim($_POST['description'] ?? '');
        $values['specification']    = trim($_POST['specification'] ?? '');
        $values['category_id']      = ($_POST['category_id'] ?? '') ?: null;
        $values['unit']             = trim($_POST['unit'] ?? 'pc') ?: 'pc';
        $values['quantity_on_hand'] = (int)($_POST['quantity_on_hand'] ?? 0);
        $values['variant_label']    = trim($_POST['variant_label'] ?? '');
        $values['stall_layer_id']   = ($_POST['stall_layer_id'] ?? '') ?: null;
        $values['generate_qr']      = !empty($_POST['generate_qr']);
        $borrow_mode = category_borrow_mode($pdo, $values['category_id'] ? (int)$values['category_id'] : null);
        $is_borrowable = borrow_mode_is_borrowable($borrow_mode) ? 1 : 0;

        $parsed = parse_variant_submission($_POST, [], $values['variant_label']);
        $variant_rows = $parsed['rows'];
        $errors = array_merge($errors, $parsed['errors']);

        if ($variant_rows && $values['variant_label'] === '') {
            $errors[] = 'Give the variant a label (e.g. "Size", "Amperage", "Color") since options were entered.';
        }
        if (!$variant_rows) {
            $values['variant_label'] = ''; // no options means no label either
        }

        $errors = array_merge($errors, validate_item_common_fields($values));
        if (!$variant_rows && $values['quantity_on_hand'] < 0) {
            $errors[] = 'Quantity on hand cannot be negative.';
        }

        // The item code field is auto-generated by category on the
        // client side and kept read-only, but if it ever arrives blank
        // (JS disabled, direct POST, etc.) fall back to generating it
        // here so a submission never fails just for a missing code.
        if ($values['item_code'] === '') {
            $values['item_code'] = next_item_code_for_category($pdo, $values['category_id'] ? (int)$values['category_id'] : null);
        }

        $image_filename = null;
        if (!$errors) {
            try {
                $image_filename = handle_item_image_upload($_FILES['image'] ?? []);
            } catch (RuntimeException $e) {
                $errors[] = $e->getMessage();
            }
        }

        if (!$errors) {
            // Up to 3 attempts: the item code came from a read-only field
            // pre-filled by JS, so on the rare chance two people submit for
            // the same category at nearly the same moment and collide on
            // the UNIQUE item_code constraint, just mint the next code and
            // retry instead of bouncing the whole form back to the user.
            $max_attempts = 3;
            for ($attempt = 1; $attempt <= $max_attempts; $attempt++) {
                try {
                    $pdo->beginTransaction();

                    $stmt = $pdo->prepare(
                        'INSERT INTO items (item_code, name, brand, description, specification, category_id, unit,
                         quantity_on_hand, is_borrowable, borrow_mode, variant_label, image_filename, stall_layer_id)
                         VALUES (:item_code, :name, :brand, :description, :specification, :category_id, :unit,
                         0, :is_borrowable, :borrow_mode, :variant_label, :image_filename, :stall_layer_id)'
                    );
                    $stmt->execute([
                        'item_code'        => $values['item_code'],
                        'name'             => $values['name'],
                        'brand'            => $values['brand'] ?: null,
                        'description'      => $values['description'] ?: null,
                        'specification'    => $values['specification'] ?: null,
                        'category_id'      => $values['category_id'],
                        'unit'             => $values['unit'],
                        'is_borrowable'    => $is_borrowable,
                        'borrow_mode'      => $borrow_mode,
                        'variant_label'    => $values['variant_label'] ?: null,
                        'image_filename'   => $image_filename,
                        'stall_layer_id'   => $values['stall_layer_id'],
                    ]);
                    $new_item_id = (int)$pdo->lastInsertId();

                    // Populated below when this item has options, so the QR
                    // generation step further down knows each option's id and
                    // starting qty and can scope tags to the specific option
                    // — mirrors how stock_in.php already scopes tags to
                    // whichever option was picked there.
                    $created_variants = [];
                    if ($variant_rows) {
                        // Each variant gets its own row, and its own initial-stock
                        // movement (which also rolls the item's aggregate total
                        // up by the same amount — see record_stock_movement()).
                        $variant_ins = $pdo->prepare(
                            'INSERT INTO item_variants (item_id, variant_value, variant_note, quantity_on_hand) VALUES (:item_id, :value, :note, 0)'
                        );
                        foreach ($variant_rows as $row) {
                            $variant_ins->execute(['item_id' => $new_item_id, 'value' => $row['value'], 'note' => $row['note']]);
                            $variant_id = (int)$pdo->lastInsertId();
                            $created_variants[] = ['id' => $variant_id, 'value' => $row['value'], 'qty' => $row['qty']];
                            if ($row['qty'] > 0) {
                                record_stock_movement(
                                    $pdo, $new_item_id, 'stock_in', $row['qty'],
                                    'initial_stock', null, $user['id'],
                                    'Initial stock at item creation (' . $row['value'] . ')', $variant_id
                                );
                            }
                        }
                    } elseif ($values['quantity_on_hand'] > 0) {
                        record_stock_movement(
                            $pdo, $new_item_id, 'stock_in', $values['quantity_on_hand'],
                            'initial_stock', null, $user['id'], 'Initial stock at item creation'
                        );
                    }

                    log_audit_event($pdo, $user, 'item_create', 'item', $new_item_id,
                        $user['full_name'] . ' added item "' . $values['name'] . '" (' . $values['item_code'] . ') to the catalog.');

                    $pdo->commit();

                    // Optional: generate QR asset tag(s) for the starting stock
                    // right away, so there's no separate trip to Register Asset.
                    // For a variant item, one lot/set-of-units is generated PER
                    // OPTION that was actually given starting stock, scoped to
                    // that option's item_variant_id — the same scoping
                    // stock_in.php already does when adding stock later. (An
                    // earlier version of this page disabled the checkbox for
                    // variant items entirely, from before assets.item_variant_id
                    // existed to make this possible — that restriction no
                    // longer applies.)
                    $created_tags = [];
                    if ($values['generate_qr']) {
                        // ['variant_id' => int|null, 'label_bit' => string, 'qty' => int]
                        $qr_lines = [];
                        if ($created_variants) {
                            foreach ($created_variants as $cv) {
                                if ($cv['qty'] > 0) {
                                    $qr_lines[] = ['variant_id' => $cv['id'], 'label_bit' => ' (' . $cv['value'] . ')', 'qty' => $cv['qty']];
                                }
                            }
                        } elseif ($values['quantity_on_hand'] > 0) {
                            $qr_lines[] = ['variant_id' => null, 'label_bit' => '', 'qty' => $values['quantity_on_hand']];
                        }

                        if ($qr_lines) {
                            $initial_location = null;
                            if (!empty($values['stall_layer_id'])) {
                                $sl_stmt = $pdo->prepare('SELECT r.room_number, s.stall_number, sl.layer_name FROM stall_layers sl JOIN stalls s ON s.id = sl.stall_id JOIN rooms r ON r.id = s.room_id WHERE sl.id = :id');
                                $sl_stmt->execute(['id' => $values['stall_layer_id']]);
                                $sl_row = $sl_stmt->fetch();
                                if ($sl_row) {
                                    $initial_location = 'Room ' . $sl_row['room_number'] . ' · Stall ' . $sl_row['stall_number'] . ' — ' . $sl_row['layer_name'];
                                }
                            }

                            try {
                                $pdo->beginTransaction();
                                foreach ($qr_lines as $line) {
                                    if (borrow_mode_is_borrowable($borrow_mode)) {
                                        for ($i = 0; $i < $line['qty']; $i++) {
                                            $tag = generate_unique_asset_tag($pdo);
                                            $ins = $pdo->prepare(
                                                'INSERT INTO assets (item_id, item_variant_id, asset_tag, serial_number, quantity, condition_note, location_note, acquired_at, registered_by)
                                                 VALUES (:item_id, :variant_id, :tag, NULL, 1, NULL, :loc, :acquired_at, :by)'
                                            );
                                            $ins->execute([
                                                'item_id'     => $new_item_id,
                                                'variant_id'  => $line['variant_id'],
                                                'tag'         => $tag,
                                                'loc'         => $initial_location,
                                                'acquired_at' => date('Y-m-d'),
                                                'by'          => $user['id'],
                                            ]);
                                            $asset_id = (int)$pdo->lastInsertId();
                                            record_asset_event(
                                                $pdo, $asset_id, 'registered', $user,
                                                'Registered as a tracked unit of ' . $values['name'] . $line['label_bit'] . ' (generated at item creation).'
                                            );
                                            $created_tags[] = $tag;
                                        }
                                    } else {
                                        $tag = generate_unique_asset_tag($pdo);
                                        $ins = $pdo->prepare(
                                            'INSERT INTO assets (item_id, item_variant_id, asset_tag, serial_number, quantity, condition_note, location_note, acquired_at, registered_by)
                                             VALUES (:item_id, :variant_id, :tag, NULL, :qty, NULL, :loc, :acquired_at, :by)'
                                        );
                                        $ins->execute([
                                            'item_id'     => $new_item_id,
                                            'variant_id'  => $line['variant_id'],
                                            'tag'         => $tag,
                                            'qty'         => $line['qty'],
                                            'loc'         => $initial_location,
                                            'acquired_at' => date('Y-m-d'),
                                            'by'          => $user['id'],
                                        ]);
                                        $asset_id = (int)$pdo->lastInsertId();
                                        record_asset_event(
                                            $pdo, $asset_id, 'registered', $user,
                                            'Registered as a lot of ' . $line['qty'] . ' ' . $values['name'] . $line['label_bit'] . ' (generated at item creation).'
                                        );
                                        $created_tags[] = $tag;
                                    }
                                }
                                log_audit_event($pdo, $user, 'asset_register', 'item', $new_item_id,
                                    $user['full_name'] . ' generated ' . count($created_tags) . ' QR tag(s) for "' . $values['name'] . '" at creation.');
                                $pdo->commit();
                            } catch (Exception $e) {
                                if ($pdo->inTransaction()) {
                                    $pdo->rollBack();
                                }
                                error_log($e->getMessage());
                                // The item itself is already saved — QR generation
                                // failing here shouldn't undo that or block the user.
                                $created_tags = [];
                            }
                        }
                    }

                    if ($created_tags) {
                        header('Location: ' . BASE_URL . '/inventory/asset_add.php?print_tags=' . urlencode(implode(',', $created_tags)));
                    } else {
                        header('Location: ' . BASE_URL . '/inventory/items.php');
                    }
                    exit;
                } catch (Exception $e) {
                    $pdo->rollBack();
                    $is_code_collision = $e instanceof PDOException && $e->getCode() === '23000'
                        && stripos($e->getMessage(), 'item_code') !== false;

                    if ($is_code_collision && $attempt < $max_attempts) {
                        $values['item_code'] = next_item_code_for_category($pdo, $values['category_id'] ? (int)$values['category_id'] : null);
                        continue;
                    }

                    delete_item_image($image_filename);
                    $errors[] = $is_code_collision
                        ? 'That item code is already in use.'
                        : 'Something went wrong. Please try again.';
                    break;
                }
            }
        }
    }
}

$categories = get_categories_with_flags($pdo);
$stalls = get_stalls($pdo);
$layers_by_stall = get_stall_layers_grouped($pdo);
// Pre-select which stall's layer options should show on load (only
// matters when re-rendering after a failed submit).
$selected_stall_id = selected_stall_for_layer($layers_by_stall, $values['stall_layer_id'] ? (int)$values['stall_layer_id'] : null);

$page_title = 'Add Item';
require __DIR__ . '/../includes/header.php';
?>
<a href="<?= BASE_URL ?>/inventory/items.php" class="back-link">&larr; Back to Catalog Management</a>
<div class="page-header">
  <div>
    <div class="eyebrow">Digital inventory catalog</div>
    <h1>Add item</h1>
  </div>
</div>

<?php foreach ($errors as $err): ?>
  <div class="alert alert-error"><?= htmlspecialchars($err) ?></div>
<?php endforeach; ?>

<div class="card" style="max-width:900px;">
  <form method="post" enctype="multipart/form-data" novalidate>
    <input type="hidden" name="csrf_token" value="<?= csrf_token() ?>">

    <div style="display:flex; gap:2rem; flex-wrap:wrap;">
    <div style="flex:1 1 340px;">
    <div class="form-section-title mt-0">Item details</div>
    <div class="form-group">
      <label for="category_id">Category</label>
      <select id="category_id" name="category_id">
        <option value="">— None —</option>
        <?php foreach ($categories as $c): ?>
          <option value="<?= $c['id'] ?>" data-borrow-mode="<?= htmlspecialchars((string)($c['borrow_mode'] ?? '')) ?>" <?= $values['category_id'] == $c['id'] ? 'selected' : '' ?>><?= htmlspecialchars((string)($c['name'] ?? '')) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
    <div class="form-group">
      <label for="item_code">Item code</label>
      <input type="text" id="item_code" name="item_code" value="<?= htmlspecialchars((string)($values['item_code'] ?? '')) ?>" readonly required class="mono" style="background:var(--paper-soft, #f6f6f4);">
    </div>
    <div class="form-group">
      <label for="name">Item name</label>
      <input type="text" id="name" name="name" value="<?= htmlspecialchars((string)($values['name'] ?? '')) ?>" required>
      <div id="existing-item-match" style="display:none; margin-top:0.5rem;"></div>
    </div>
    <div class="form-group">
      <label for="brand">Brand / Supplier <span class="text-muted-normal">(optional)</span></label>
      <input type="text" id="brand" name="brand" value="<?= htmlspecialchars((string)($values['brand'] ?? '')) ?>" placeholder='e.g. "ASUKI", "BOSCH"'>
    </div>
    <div class="form-group" style="margin-bottom:0;">
      <label for="description">Description</label>
      <textarea id="description" name="description" rows="3" style="width:100%; padding:0.55rem 0.7rem; border:1px solid var(--line); border-radius:6px; font-family:var(--font-body);"><?= htmlspecialchars((string)($values['description'] ?? '')) ?></textarea>
    </div>
    </div>

    <div style="flex:1 1 340px; border-left:1px solid var(--line); padding-left:2rem;">
    <div class="form-section-title mt-0">Stock, location &amp; photo</div>

    <div style="display:flex; gap:1rem;">
      <div class="form-group" style="flex:2;">
        <label for="unit_select">Unit</label>
        <select id="unit_select">
          <?php foreach (item_unit_options() as $val => $label): ?>
            <option value="<?= htmlspecialchars($val) ?>"><?= htmlspecialchars($label) ?></option>
          <?php endforeach; ?>
          <option value="__other__">Other (specify)…</option>
        </select>
        <input aria-label="Unit of measurement" type="text" id="unit_other" name="unit_other" placeholder="Enter unit" style="display:none; margin-top:0.5rem;">
        <input type="hidden" id="unit" name="unit" value="<?= htmlspecialchars((string)($values['unit'] ?? '')) ?>">
      </div>
      <div class="form-group" style="flex:1; max-width:150px;" id="plainQtyGroup">
        <label for="quantity_on_hand">Quantity</label>
        <div class="qty-stepper">
          <button type="button" class="qty-stepper-btn" id="qtyOnHandMinus" aria-label="Lower the quantity">&minus;</button>
          <input type="text" inputmode="numeric" id="quantity_on_hand" name="quantity_on_hand" value="<?= $values['quantity_on_hand'] ?>">
          <button type="button" class="qty-stepper-btn" id="qtyOnHandPlus" aria-label="Raise the quantity">&plus;</button>
        </div>
      </div>
    </div>

    <div class="form-divider"></div>

    <div style="display:flex; gap:1rem;">
      <div class="form-group flex-1">
        <label for="stall_select">Room / Stall</label>
        <select id="stall_select">
          <option value="">— None —</option>
          <?php foreach ($stalls as $s): ?>
            <option value="<?= $s['id'] ?>" <?= $selected_stall_id == $s['id'] ? 'selected' : '' ?>>Room <?= (int)$s['room_number'] ?> · Stall <?= (int)$s['stall_number'] ?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group flex-1">
        <label for="stall_layer_id">Layer</label>
        <select id="stall_layer_id" name="stall_layer_id"></select>
      </div>
    </div>

    <div class="form-group">
      <label style="display:flex; align-items:center; gap:0.5rem; font-weight:400;">
        <input type="checkbox" id="hasVariantsToggle" <?= $values['variant_label'] !== '' ? 'checked' : '' ?>>
        This item has multiple options (size, amperage, color, etc.) that need separate stock counts
      </label>
    </div>

    <div id="variantSection" style="display:<?= $values['variant_label'] !== '' ? 'block' : 'none' ?>;">
      <div class="form-group">
        <label for="variant_label">Variant label</label>
        <input type="text" id="variant_label" name="variant_label" value="<?= htmlspecialchars((string)($values['variant_label'] ?? '')) ?>" placeholder='e.g. "Size", "Amperage", "Color"'>
      </div>

      <div class="form-group" id="variantRowsGroup">
        <label>Options &amp; starting stock</label>
        <div id="variantRows">
          <?php
          $prefill_rows = $variant_rows ?: [['value' => '', 'qty' => 0, 'note' => '']];
          foreach ($prefill_rows as $row): ?>
            <div class="variant-row" style="display:flex; gap:0.5rem; margin-bottom:0.5rem;">
              <input aria-label="Variant value" type="text" name="variant_value[]" value="<?= htmlspecialchars((string)($row['value'] ?? '')) ?>" placeholder="e.g. 10A" style="flex:2;">
              <input aria-label="Starting quantity" type="text" inputmode="numeric" name="variant_qty[]" value="<?= (int)$row['qty'] ?>" placeholder="Qty" class="flex-1">
              <input aria-label="Variant description" type="text" name="variant_note[]" value="<?= htmlspecialchars($row['note'] ?? '') ?>" placeholder="Note (optional)" style="flex:2;">
              <button type="button" class="btn btn-outline btn-sm variant-row-remove">Remove</button>
            </div>
        <?php endforeach; ?>
      </div>
      <button type="button" id="addVariantRow" class="btn btn-outline btn-sm">+ Add option</button>
    </div>
    </div>

    <div class="form-group" id="generateQrGroup">
      <label style="display:flex; align-items:center; gap:0.5rem; font-weight:400;">
        <input type="checkbox" id="generate_qr" name="generate_qr" value="1" <?= $values['generate_qr'] ? 'checked' : '' ?>>
        Generate QR tag(s) now
      </label>
      <span id="generateQrHint" style="font-size:0.8rem; color:var(--ink-soft);">Auto-generates QR per unit.</span>
    </div>

    <div class="form-divider"></div>

    <div class="photo-panel">
      <div class="form-group" style="margin-bottom:0;">
        <label for="image">Photo <span class="text-muted-normal">(max 3 MB)</span></label>
        <input type="file" id="image" name="image" accept=".jpg,.jpeg,.png,.webp">
      </div>
    </div>

    <button type="submit" class="btn btn-primary" style="margin-top:1.1rem; width:100%;">Add item</button>
    </div>
    </div>
  </form>
</div>

<script>
  window.ItemFormData = {
    layersByStall: <?= json_encode($layers_by_stall) ?>,
    selectedLayerId: <?= json_encode($values['stall_layer_id'] ? (int)$values['stall_layer_id'] : null) ?>,
    autoItemCode: true,
    itemCodeUrl: <?= json_encode(BASE_URL . '/inventory/item_code_ajax.php') ?>,
    itemMatchUrl: <?= json_encode(BASE_URL . '/inventory/item_match_ajax.php') ?>,
    stockInBaseUrl: <?= json_encode(BASE_URL . '/inventory/stock_in.php') ?>,
    currentUnit: <?= json_encode($values['unit']) ?>
  };
</script>
<script src="<?= BASE_URL ?>/assets/js/item-form.js"></script>
<script>
  (function () {
    var categorySelect = document.getElementById('category_id');
    var qrCheckbox = document.getElementById('generate_qr');
    var qrHint = document.getElementById('generateQrHint');
    var variantToggle = document.getElementById('hasVariantsToggle');
    // Once the user manually touches the checkbox, stop auto-deciding it
    // for them on every category change. On a failed-submit redisplay,
    // treat their prior choice as already "touched" so it isn't overwritten.
    var qrTouchedByUser = <?= $_SERVER['REQUEST_METHOD'] === 'POST' ? 'true' : 'false' ?>;

    if (!categorySelect || !qrCheckbox) { return; }
    qrCheckbox.addEventListener('change', function () { qrTouchedByUser = true; });

    function syncQr() {
      var hasVariants = variantToggle && variantToggle.checked;
      qrCheckbox.disabled = false;
      qrHint.textContent = hasVariants
        ? 'Auto-generates QR per variant.'
        : 'Auto-generates QR per unit.';
      if (!qrTouchedByUser) {
        var opt = categorySelect.options[categorySelect.selectedIndex];
        var mode = opt ? opt.dataset.borrowMode : null;
        qrCheckbox.checked = (mode === 'borrow' || mode === 'choice');
      }
    }

    categorySelect.addEventListener('change', syncQr);
    if (variantToggle) { variantToggle.addEventListener('change', syncQr); }
    syncQr();
  })();
</script>

<?php require __DIR__ . '/../includes/footer.php'; ?>
